services:
  _defaults:
    autowire: true

  HeimrichHannot\SyndicationTypeBundle\SyndicationType\SyndicationTypeCollection: ~

  HeimrichHannot\SyndicationTypeBundle\SyndicationLink\SyndicationLinkFactory: ~
  HeimrichHannot\SyndicationTypeBundle\SyndicationLink\SyndicationLinkProviderGenerator: ~
  HeimrichHannot\SyndicationTypeBundle\SyndicationLink\SyndicationLinkRenderer: ~

  HeimrichHannot\SyndicationTypeBundle\Dca\:
    resource: '../../Dca/*'
    public: true

  HeimrichHannot\SyndicationTypeBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    public: true

  HeimrichHannot\SyndicationTypeBundle\EventListener\Dca\FieldOptionsCallbackListener:
    public: true
    calls:
      - [ setReaderConfigUtil, [ '@?HeimrichHannot\ReaderBundle\Util\ReaderConfigUtil' ] ]

  HeimrichHannot\SyndicationTypeBundle\SyndicationType\Concrete\:
    resource: '../../SyndicationType/Concrete/*'
    tags: [ 'huh.syndication_type.type' ]

  HeimrichHannot\SyndicationTypeBundle\ConfigElementType\:
    resource: '../../ConfigElementType/*'
    tags: [ 'huh.reader.config_element_type' ]

